// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuZSAN2U56u9yITI4Ldw4hPHAeAzrLzWc',
    appId: '1:292981245129:web:5ccef1aafe8f53d927f918',
    messagingSenderId: '292981245129',
    projectId: 'pawfectcare-unzela-2026',
    authDomain: 'pawfectcare-unzela-2026.firebaseapp.com',
    storageBucket: 'pawfectcare-unzela-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmu0kc2C3pY6scF_-uN218bEMcI6VdICU',
    appId: '1:292981245129:android:33e70096950e9ce627f918',
    messagingSenderId: '292981245129',
    projectId: 'pawfectcare-unzela-2026',
    storageBucket: 'pawfectcare-unzela-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6kTQbngjCPp2NQnMNqG_-8LtIqc0M2NE',
    appId: '1:292981245129:ios:c4866871522ccbd927f918',
    messagingSenderId: '292981245129',
    projectId: 'pawfectcare-unzela-2026',
    storageBucket: 'pawfectcare-unzela-2026.firebasestorage.app',
    iosBundleId: 'com.pawfectcare.app.pawfectCare',
  );
}
